name: Deploy C# ASP.NET Core 8.0 API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
    - name: 1. Fetch latest code from Git
      uses: actions/checkout@v4

    - name: 2. Publish and deploy using local dotnet
      run: |
        /home/os-joan.chen/.dotnet/dotnet publish -c Release -o /home/os-joan.chen/app-backend/api-site